POST https://cloud.linked-go.com:449/crmservice/api/app/user/login
Content-Type: application/json; charset=utf-8

{"userName": "jbr@jbr.dk", "password": "035d5667404f9ee80f5c81fbb49afea0"}

###
POST https://cloud.linked-go.com:449/crmservice/api/app/device/deviceList
Content-Type: application/json; charset=utf-8
x-token: ibQgkum/njMp2raXi7hR6QzY5wjB/vtPDaaRkhDfj3jRn13Xlalh5hS95vFP4uWvThAq0toh1iDxP6nFmwY1yQ==

###

POST https://cloud.linked-go.com:449/crmservice/api/app/device/getDataByCode
Content-Type: application/json; charset=utf-8
x-token: TMME+1HvFcJzvcngreFgAaBkPJfXxrPoX33DA/i/6+9hgctb+NqdXEc6UJt2exzVThAq0toh1iDxP6nFmwY1yQ==

{"deviceCode":  "289C6E13334C",
  "protocal_codes": ["Power","Mode","Manual-mute","T01","T02","2074","2075","2076","2077","H03","Set_Temp","R08","R09","R10","R11","R01","R02","R03","T03","1158","1159","F17","H02","T04","T05","T06","T07","T12","T14"]
}
